spring.application.name=demo
spring.http.codecs.max-in-memory-size=16MB
# Fincrux API Configuration
fincrux.api.url=https://api.fincrux.org
fincrux.api.key=bFPnztz8bAGKpw4QkBpk7p
# Cache Configuration
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000
# Logging Configuration
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
logging.level.org.springframework.cache=DEBUG
logging.level.org.springframework.data.redis=DEBUG